spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: LycorisRecoil

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: cn.zhouhaixian.bookingapi.controller

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl